version: '3.8'

services:

  release:
    image: johnnyhuy/actions-discord-git-webhook/release:latest
    build:
      context: .
      dockerfile: release.Dockerfile
    volumes:
      - ".:/app"
    working_dir: /app
    environment:
      - CONVENTIONAL_GITHUB_RELEASER_TOKEN