name: Publish Git Commits

on: [push]

jobs:
  git:
    name: Git Commits
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@${{ steps.branch-name.outputs.current_branch }
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: 12B92E
