name: Publish Git Commits

on: [push]

jobs:
  git:

    name: Git Commits
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
    - uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@feature/test-cases
      with:
        webhook_url: ${{ secrets.DISCORD_CHANGELOG_WEBHOOK }}
        color: 12B92E
