name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          docker-compose -f docker-compose.test.yml build test
          docker-compose -f docker-compose.test.yml run --rm test

      - name: Set Git user
        run: |
          git config user.name "georgelilaccat"
          git config user.email "95064644+georgelilaccat@users.noreply.github.com"

      - name: Build
        run: docker-compose build release

      - name: Version
        run: docker-compose run --rm release standard-version

      - name: Push tags
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.SERVICE_GITHUB_TOKEN }}
          branch: main
          tags: true

      - name: Release
        run: docker-compose run --rm release conventional-github-releaser
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.SERVICE_GITHUB_TOKEN }}
