name: Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: |
          docker-compose -f docker-compose.test.yml build test
          docker-compose -f docker-compose.test.yml run --rm test

      - name: Version
        run: |
          docker-compose build release
          docker-compose run --rm release standard-version
          git push --follow-tags origin main
          docker-compose run --rm release conventional-github-releaser
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GITHUB_TOKEN }}